version: '3'
services:
  jws-config:
    build: .
    image: cxn/jws
    command: /opt/chemaxon/jws/jws-config/run-jws-config
    environment: 
      - "EUREKA_URI=http://jws-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jws-config:8888/"
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - "logdata:/opt/chemaxon/jws/logs"
      - "config:/opt/chemaxon/jws/jws-config/common-config"
  jws-discovery:
    build: .
    image: cxn/jws
    command: /opt/chemaxon/jws/jws-discovery/run-jws-discovery
    environment: 
      - "EUREKA_URI=http://jws-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jws-config:8888/"
    ports:
      - "8761:8761"
    restart: unless-stopped
    volumes:
      - "logdata:/opt/chemaxon/jws/logs"
  jws-calculations:
    build: .
    image: cxn/jws
    command: /opt/chemaxon/jws/jws-calculations/run-jws-calculations
    environment: 
      - "EUREKA_URI=http://jws-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jws-config:8888/" 
    ports:
      - "8084:8064"
    restart: unless-stopped
    volumes:
      - "logdata:/opt/chemaxon/jws/logs"
      - "license:/opt/chemaxon/jws/license"
  jws-db:
    build: .
    image: cxn/jws
    command: /opt/chemaxon/jws/jws-db/run-jws-db
    environment: 
      - "EUREKA_URI=http://jws-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jws-config:8888/" 
    ports:
      - "8082:8062"
    restart: unless-stopped
    volumes:
      - "logdata:/opt/chemaxon/jws/logs"
      - "dbdata:/opt/chemaxon/jws/jws-db/data/"
      - "license:/opt/chemaxon/jws/license"
  jws-io:
    build: .
    image: cxn/jws
    command: /opt/chemaxon/jws/jws-io/run-jws-io
    environment: 
      - "EUREKA_URI=http://jws-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jws-config:8888/" 
    ports:
      - "8081:8061"
    restart: unless-stopped
    volumes:
      - "logdata:/opt/chemaxon/jws/logs"
      - "license:/opt/chemaxon/jws/license"
  jws-structure:
    build: .
    image: cxn/jws
    command: /opt/chemaxon/jws/jws-structure/run-jws-structure
    environment: 
      - "EUREKA_URI=http://jws-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jws-config:8888/" 
    ports:
      - "8083:8063"
    restart: unless-stopped
    volumes:
      - "logdata:/opt/chemaxon/jws/logs"
      - "license:/opt/chemaxon/jws/license"
  jws-markush:
    build: .
    image: cxn/jws
    command: /opt/chemaxon/jws/jws-markush/run-jws-markush
    environment: 
      - "EUREKA_URI=http://jws-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jws-config:8888/" 
    ports:
      - "8085:8065"
    restart: unless-stopped
    volumes:
      - "logdata:/opt/chemaxon/jws/logs"
      - "license:/opt/chemaxon/jws/license"
  jws-gateway:
    build: .
    image: cxn/jws
    command: /opt/chemaxon/jws/jws-gateway/run-jws-gateway
    environment: 
      - "EUREKA_URI=http://jws-discovery:8761/"
      - "CONFIG_SERVER_URI=http://jws-config:8888/" 
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "logdata:/opt/chemaxon/jws/logs"
    
volumes:
   logdata:
   dbdata:
   license:
   config: